version: "3.3"
services:
  app:
    build: .
    volumes:
      - .:/nlb-telegram-bot
    command: pipenv run python __init__.py
  db:
    image: postgres:13-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
