version: "3.3"
services:
  app:
    build: .
    volumes:
      - .:/nlb-telegram-bot
    # TODO: pipenv run alembic upgrade head && pipenv run python -u __init__.py
    command: pipenv run python -u __init__.py
    # TODO: commented for speed, uncomment for stability
    # depends_on:
    #   - db
    restart: on-failure
  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nlb

volumes:
  db-data: {}
