version: "2.3"
services:
  app:
    build: .
    container_name: nlb_app
    volumes:
      - .:/nlb-telegram-bot
    command: bash -c "pipenv run alembic upgrade head && pipenv run python -u __init__.py"
    depends_on:
      - db
    restart: on-failure
    mem_limit: 100m

  db:
    image: postgres:13-alpine
    container_name: nlb_db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db-data: {}
